baseurl = "http://example.org"
title = "Mon Blog"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "Mon Blog"
description = "aether Hugo theme for blogs"
bgimg = "img/ignasi_pattern_s.png"
